/* ─── Design tokens ──────────────────────────────────────────── */
export const COLORS = [
  "#C8976E",
  "#5B9EAD",
  "#2D5F6E",
  "#C4A24D",
  "#8B6B4A",
  "#7ABCCC",
  "#A0522D",
  "#4E8098",
  "#D4956A",
  "#6B8E6E",
  "#9B7B9A",
  "#C9A96E",
];

export const TOOLTIP_STYLE = {
  background: "#FDFAF6",
  border: "1px solid #E8DDD0",
  borderRadius: 10,
  fontSize: 12,
  color: "#3D2B1F",
  boxShadow: "0 4px 20px rgba(0,0,0,0.08)",
};

/* ─── Styles ─────────────────────────────────────────────────── */
export const styles = {
  root: {
    minHeight: "100vh",
    background: "#F5EFE6",
    fontFamily: "'Georgia', 'Times New Roman', serif",
  },
  header: {
    background: "#FDFAF6",
    borderBottom: "1px solid #E8DDD0",
    backdropFilter: "blur(8px)",
  },
  headerInner: {
    maxWidth: 1280,
    margin: "0 auto",
    padding: "18px 28px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerBrand: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  headerLogo: {
    width: 36,
    height: 36,
    borderRadius: 8,
    background: "#3D2B1F",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    margin: 0,
    fontSize: 15,
    fontWeight: 600,
    color: "#3D2B1F",
    letterSpacing: "0.02em",
  },
  headerSub: {
    margin: 0,
    fontSize: 11,
    color: "#9C7B65",
    fontFamily: "sans-serif",
  },
  liveBadge: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "#F5EFE6",
    border: "1px solid #E8DDD0",
    borderRadius: 20,
    padding: "5px 12px",
    fontSize: 11,
    color: "#7A6050",
    fontFamily: "sans-serif",
  },
  main: {
    maxWidth: 1280,
    margin: "0 auto",
    padding: "28px 28px 60px",
  },
  tabRow: {
    display: "flex",
    gap: 4,
    marginBottom: 28,
    background: "#EDE5D8",
    borderRadius: 10,
    padding: 4,
    width: "fit-content",
  },
  tab: {
    padding: "8px 20px",
    borderRadius: 7,
    border: "none",
    cursor: "pointer",
    fontSize: 13,
    fontFamily: "sans-serif",
    fontWeight: 500,
    transition: "all 0.15s ease",
    letterSpacing: "0.01em",
  },
  tabActive: {
    background: "#FDFAF6",
    color: "#3D2B1F",
    boxShadow: "0 1px 4px rgba(0,0,0,0.10)",
  },
  tabInactive: {
    background: "transparent",
    color: "#9C7B65",
  },
  tabContent: {
    display: "flex",
    flexDirection: "column",
    gap: 24,
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: 14,
  },
  statCard: {
    background: "#FDFAF6",
    border: "1px solid #E8DDD0",
    borderRadius: 14,
    padding: "20px 22px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    boxShadow: "0 1px 6px rgba(0,0,0,0.04)",
    minWidth: 0,
    overflow: "hidden",
  },
  statLabel: {
    margin: 0,
    fontSize: 10,
    fontFamily: "sans-serif",
    fontWeight: 600,
    letterSpacing: "0.10em",
    textTransform: "uppercase",
    color: "#9C7B65",
  },
  statValue: {
    margin: "6px 0 4px",
    fontSize: 24,
    fontWeight: 700,
    color: "#3D2B1F",
    lineHeight: 1.1,
    letterSpacing: "-0.02em",
    wordBreak: "break-word",
    overflowWrap: "break-word",
  },
  statHint: {
    margin: 0,
    fontSize: 11,
    color: "#B09880",
    fontFamily: "sans-serif",
  },
  statIcon: {
    background: "#F5EFE6",
    borderRadius: 9,
    padding: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  chartsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: 14,
  },
  card: {
    background: "#FDFAF6",
    border: "1px solid #E8DDD0",
    borderRadius: 14,
    padding: "20px 22px",
    boxShadow: "0 1px 6px rgba(0,0,0,0.04)",
  },
  span2: { gridColumn: "span 2" },
  span3: { gridColumn: "span 3" },
  cardHeader: { marginBottom: 16 },
  cardTitle: {
    margin: 0,
    fontSize: 14,
    fontWeight: 600,
    color: "#3D2B1F",
  },
  cardDesc: {
    margin: "3px 0 0",
    fontSize: 11,
    color: "#9C7B65",
    fontFamily: "sans-serif",
  },
  sectionLabel: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    margin: "4px 0",
  },
  sectionLabelLine: {
    flex: 1,
    height: 1,
    background: "#E8DDD0",
  },
  sectionLabelText: {
    fontSize: 10,
    fontFamily: "sans-serif",
    fontWeight: 700,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    color: "#B09880",
    whiteSpace: "nowrap",
  },
  searchInput: {
    width: "100%",
    padding: "9px 12px 9px 34px",
    border: "1px solid #E8DDD0",
    borderRadius: 9,
    fontSize: 13,
    fontFamily: "sans-serif",
    color: "#3D2B1F",
    background: "#FDFAF6",
    outline: "none",
    boxSizing: "border-box",
  },
  roomHighlight: {
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
    padding: "12px 0",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 13,
    fontFamily: "sans-serif",
  },
  th: {
    textAlign: "left",
    padding: "10px 14px",
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    color: "#9C7B65",
    borderBottom: "2px solid #E8DDD0",
  },
  td: {
    padding: "10px 14px",
    color: "#5A3E2B",
    borderBottom: "1px solid #F0E8DE",
    fontSize: 13,
  },
};
